<a href="https://colab.research.google.com/github/bhardwaj1230/algorithms/blob/master/Permutation_using_backtracking.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Using permutaion function :

In [0]:
import numpy as np
from itertools import permutations

A = np.array([[0,1,1,1],[1,0,0,1],[1,0,0,0],[1,1,0,0]])

B= np.array([[0,1,1,0],[1,0,1,0],[1,1,0,1],[0,0,1,0]])

In [57]:
def is_equivalent(A, B):
    assert A.shape[0] == A.shape[1]
    assert B.shape[0] == B.shape[1]
    if A.shape != B.shape:
        return False
    n = A.shape[0]
    for perm in permutations(range(n), n):
        perm = np.array(perm)
        C = A[perm[:, None], perm]
        if np.all(C == B):
            return True
    return False

is_equivalent(A, B)

True

# Using Backtracking  with repetition :

In [45]:
import numpy as np
import sys

A = np.array([[0,1,1,1],[1,0,0,1],[1,0,0,0],[1,1,0,0]])
B= np.array([[0,1,1,0],[1,0,1,0],[1,1,0,1],[0,0,1,0]])

def permute(a, l, r): 
    if l==r:
        perm = np.array(a)
        C = A[perm[:, None], perm]
        if np.all(C == B):
            
            print('Current Permutation :',perm, '\nMatrix of current Permutation :\n' ,C)
            print('\nMatching with :\n', B)
            print('\n Its a match !!!\n\n')
            #sys.exit()
        
    else: 
        for i in range(l,r+1): 
            a[l], a[i] = a[i], a[l] 
            permute(a, l+1, r) 
            a[l], a[i] = a[i], a[l] # backtrack 
            
n = A.shape[0]            
p = list(range(n))
permute(p, 0, n-1) 

Current Permutation : [1 3 0 2] 
Matrix of current Permutation :
 [[0 1 1 0]
 [1 0 1 0]
 [1 1 0 1]
 [0 0 1 0]]

Matching with :
 [[0 1 1 0]
 [1 0 1 0]
 [1 1 0 1]
 [0 0 1 0]]

 Its a match !!!


Current Permutation : [3 1 0 2] 
Matrix of current Permutation :
 [[0 1 1 0]
 [1 0 1 0]
 [1 1 0 1]
 [0 0 1 0]]

Matching with :
 [[0 1 1 0]
 [1 0 1 0]
 [1 1 0 1]
 [0 0 1 0]]

 Its a match !!!




#Using Backtracking without repetition:

In [0]:
def permute_backtracking(A, B, p, n, k, depth, visited, current_visit, all_permutation):
    
    assert A.shape[0] == A.shape[1]
    assert B.shape[0] == B.shape[1]
    if A.shape != B.shape:
        return False
    
    if depth == k: #end condition
        all_permutation.append(current_visit[::]) # use deepcopy because current_visit is tracking all partial solution, it eventually become []
        
        perm = np.array(all_permutation[-1])
        C = A[perm[:, None], perm]
        if np.all(C == B):
            print('\n\n Found a Match !!!\n\n')
            return

    for i in range(n):
        if not visited[i]:
      # generate the next solution from current_visit
            current_visit.append(p[i])
            visited[i] = True
            print('Step --> ',current_visit)
            # move to the next solution
            permute_backtracking(A, B, p, n, k, depth+1, visited, current_visit, all_permutation)

            #backtrack to previous partial state
            current_visit.pop()
            print('Backtracking : ', current_visit)
            visited[i] = False
    return

In [55]:
A = np.array([[0,1,1,1],[1,0,0,1],[1,0,0,0],[1,1,0,0]])
B= np.array([[0,1,1,0],[1,0,1,0],[1,1,0,1],[0,0,1,0]])	
		   

n = A.shape[0]
p = list(range(n))
visited = [False] * n
permute_backtracking(A, B, p, n, n, 0, visited, [], [])


Step -->  [0]
Step -->  [0, 1]
Step -->  [0, 1, 2]
Step -->  [0, 1, 2, 3]
Backtracking :  [0, 1, 2]
Backtracking :  [0, 1]
Step -->  [0, 1, 3]
Step -->  [0, 1, 3, 2]
Backtracking :  [0, 1, 3]
Backtracking :  [0, 1]
Backtracking :  [0]
Step -->  [0, 2]
Step -->  [0, 2, 1]
Step -->  [0, 2, 1, 3]
Backtracking :  [0, 2, 1]
Backtracking :  [0, 2]
Step -->  [0, 2, 3]
Step -->  [0, 2, 3, 1]
Backtracking :  [0, 2, 3]
Backtracking :  [0, 2]
Backtracking :  [0]
Step -->  [0, 3]
Step -->  [0, 3, 1]
Step -->  [0, 3, 1, 2]
Backtracking :  [0, 3, 1]
Backtracking :  [0, 3]
Step -->  [0, 3, 2]
Step -->  [0, 3, 2, 1]
Backtracking :  [0, 3, 2]
Backtracking :  [0, 3]
Backtracking :  [0]
Backtracking :  []
Step -->  [1]
Step -->  [1, 0]
Step -->  [1, 0, 2]
Step -->  [1, 0, 2, 3]
Backtracking :  [1, 0, 2]
Backtracking :  [1, 0]
Step -->  [1, 0, 3]
Step -->  [1, 0, 3, 2]
Backtracking :  [1, 0, 3]
Backtracking :  [1, 0]
Backtracking :  [1]
Step -->  [1, 2]
Step -->  [1, 2, 0]
Step -->  [1, 2, 0, 3]
Backtrack